

# This file was *autogenerated* from the file e_symm_decompositions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6)### Code to compute and format TriCat_n(q,t) in terms of elementary symmetric functions

R = PolynomialRing(ZZ, names=('q', 't',)); (q, t,) = R._first_ngens(2)
E = PolynomialRing(QQ, names=('e1', 'e2',)); (e1, e2,) = E._first_ngens(2)


# Compute longest chain from v to all other vertices in graph reachable from v;
# exploits fact that poset is a DAG
def longest_chain_lengths(G, v):
    top_order = G.topological_sort()
    distances = {v: _sage_const_0 }
    for v in top_order:
        if v not in distances:
            continue
        for w in G.neighbor_out_iterator(v):
            if w in distances:
                distances[w] = max(distances.get(w), distances[v] + _sage_const_1 )
            else:
                distances[w] = distances[v] + _sage_const_1 
    return distances


def i(b,n):
    P = posets.TamariLattice(n)
    H = P.hasse_diagram().reverse()
    distances = longest_chain_lengths(H,b)
    f = _sage_const_0 
    for key in distances:
        f = f+q**(distances[key])
    return f


# Converts a Dyck word to a Dyck path
def path(b):
    temp = DyckWord(list(b[_sage_const_0 :-_sage_const_1 ])).to_non_decreasing_parking_function()
    path = []
    for i in temp:
        path.append(i-_sage_const_1 )
    return path


# Returns a polynomial in t
def dinv(b,n):
    c = []
    path_b = path(b)
    for i in range(len(path_b)):
        c.append(i-path_b[i])
    count = _sage_const_0 
    for j in range(_sage_const_0 ,n):
        for i in range(_sage_const_0 ,j):
            if c[i] - c[j] == _sage_const_0  or c[i] - c[j] == _sage_const_1 :
                count = count+_sage_const_1 
    return t**count


# Computes TriCat_n^{BPR}(q,t)
def TriCat(n):
    P = posets.TamariLattice(n)
    f = _sage_const_0 

    for b in P:
        f = f + i(b,n)*dinv(b,n)
    return f


# Take a symmetric polynomial f in variables q,t and return its expansion in terms of elementary symmetric functions
# (Courtesy of Claude; I've checked this)
def elementary_expansion(f):
    f = R(f)

    if f != f.subs({q: t, t: q}):
        raise ValueError("Input polynomial is not symmetric in q, t")

    result = E(_sage_const_0 )

    while f != _sage_const_0 :
        # Leading coefficient with respect to lex ordering (q > t)
        c = f.leading_coefficient()

        # Exponents of the leading monomial with respect to lex ordering (q > t)
        a,b = f.lm().exponents()[_sage_const_0 ]  # q^a * t^b

        # Since c(q + t)^{a-b} q^b t^b = c\sum_{i=0}^{a-b} \binom{a-b}{i} q^{a-i}t^{b+i} 
        # = c q^a t^b + c\sum_{i=1}^{a-b} \binom{a-b}{i} q^{a-i}t^{b+i}, the difference
        # f(q,t) - c(q + t)^{a-b} (qt)^b strictly smaller leading coefficient that f with
        # respect to the lex-ordering with q > t.
        term = c * e1**(a - b) * e2**b
        result += term

        # Subtract off its expansion back in q,t
        g = c * (q + t)**(a - b) * (q * t)**b
        f = f - g

    return result


# Compile table of monomial coefficients for TriCat_n^{BPR}(q,t) in terms of e1 & e2
def TriCat_elementary_expansion(a,b):
    polynomials = []
    degrees_in_e2 = []
    for n in (ellipsis_range(a,Ellipsis,b)):
        f = elementary_expansion(TriCat(n))
        polynomials.append(f)
        degrees_in_e2.append(f.degree(e2))
    
    max_deg_2 = max(degrees_in_e2)
    
    Rows = []
    for n in (ellipsis_range(a,Ellipsis,b)):
        f = polynomials.pop(_sage_const_0 )
        deg_1 = f.degree(e1)

        header = ["n = " + str(n)]
        for j in (ellipsis_range(_sage_const_0 ,Ellipsis,max_deg_2)):
            header.append("$e_2^{" + str(j) + "}$")

        Rows.append(header)

        for i in (ellipsis_range(_sage_const_0 ,Ellipsis,deg_1)):
            row = ["$e_1^{" + str(i) + "}$"]
            for j in (ellipsis_range(_sage_const_0 ,Ellipsis,max_deg_2)):
                # Add coefficient of e1^i * e2^j to table
                row.append(f.monomial_coefficient(e1**i * e2**j))
            Rows.append(row)

    return table(Rows,frame=True,align='center',header_row=True,header_column=True)

print(latex(TriCat_elementary_expansion(_sage_const_4 ,_sage_const_6 )))

